name: mg_tools
description: A Dart CLI tool to generate dart Freezed models from .dto.json files, with nested support and auto DateTime detection.
homepage: https://github.com/mohamadalghanem474/mg_tools
repository: https://github.com/mohamadalghanem474/mg_tools
issue_tracker: https://github.com/mohamadalghanem474/mg_tools/issues
documentation: https://github.com/mohamadalghanem474/mg_tools#readme
version: 1.0.14

environment:
  sdk: ^3.6.2

dependencies:
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0

executables:
  mg_tools: mg_tools

screenshots:
  - description: The mg_tools package logo.
    path: screenshots/logo.png
