name: mg_tools
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/mohamadalghanem474/mg_tools

environment:
  sdk: ^3.6.2

dependencies:
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0

executables:
  mg_tools: mg_tools
