name: mg_tools
description: A Dart tool to generate dart Freezed models from .dto.json files, nested objects support and auto DateTime detection.
homepage: https://github.com/mohamadalghanem474/mg_tools
repository: https://github.com/mohamadalghanem474/mg_tools
issue_tracker: https://github.com/mohamadalghanem474/mg_tools/issues
documentation: https://github.com/mohamadalghanem474/mg_tools#readme
version: 1.0.16

environment:
  sdk: ^3.6.2

dependencies:
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0

topics: 
  - codegen
  - freezed
  - json
  - models
  - tools

screenshots:
  - description: The mg_tools package logo.
    path: screenshots/logo.png
