name: mg_tools
description: A Dart CLI tool to generate Freezed & JsonSerializable models from .dto.json files, with nested support and auto DateTime detection.
version: 1.0.4
repository: https://github.com/mohamadalghanem474/mg_tools

environment:
  sdk: ^3.6.2

dependencies:
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0

executables:
  mg_tools: mg_tools
